spring.application.name=VenteEnchere
# changer le port du serveur Web 
server.port = 8082
# definir les informations de connxn \u00c3\u00a0 la BD
spring.datasource.url = jdbc:postgresql://localhost:5432/venteenchere
spring.datasource.username = postgres
spring.datasource.password = 2003
spring.datasource.Driver-class-Name = org.postgresql.Driver
# definir les proprietes de l'ORM
# a chaque demarrage, si table non existante, la cr\u00c3\u00a9er, sinon ne rien faire
spring.jpa.hibernate.ddl-auto = update 
# afficher les requetes SQL equivalentes des instructions JAVA
spring.jpa.show-sql = true
